name: Lucasismyname
favicon: null
layout_spectrum: 0.4456
typography_spectrum: 0.18607
title: Lucas is my name
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#273038'
    - '#9ccb88'
    - '#f3785a'
    - '#82a778'
    - '#41514c'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
