name: Lucasismyname
favicon: null
layout_spectrum: 0.24001
typography_spectrum: 0.18607
title: Lucas is my name
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1b30'
    - '#742875'
    - '#c2e5d8'
    - '#b3c1c5'
    - '#967aa0'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
